/* Day 1 Canva deck — speaker notes per page, edited from the deck's own notes, plus a scenario for
   the room on every page. "notes" is the spoken script (why → talk it through → walk through it →
   ask the room); paste it back into Canva's notes panel as is. Presenter view shows it page by page. */
window.DECK_NOTES = Object.assign(window.DECK_NOTES || {}, {
 1: [
  {
   "page": 1,
   "title": "Property Damage Training (title)",
   "notes": "Good day, everyone, and welcome to Day 1 of Property Damage Claims Training! This week you'll learn how to handle a client's property damage claim from the very first call to the final payment: the car, the rental, towing and storage, and getting the vehicle repaired or valued fairly. Take a look at the photo: that's an adjuster writing up a damaged car. Every number on that clipboard ends up affecting our client, and part of our job is making sure those numbers are right. Today is about the foundations, and you'll see the plan on the next slide. Before we start: has anyone here ever had their own car damaged in an accident? What was the hardest part?",
   "scenario": "Picture this: it's Monday morning and a new client calls. Her car was hit three days ago. It's sitting at a tow yard that charges storage every day, she has no car to get to work, and the adjuster hasn't called her back. She asks you, \"What happens now?\" By the end of this week, you'll know exactly what to do for her, and in what order. Keep her in mind; we'll follow her claim all week."
  },
  {
   "page": 2,
   "title": "Table of Contents",
   "notes": "Here's our scope for today, in four parts. First, an introduction and overview of property damage: what a PD claim covers and how it sits next to the client's injury claim. Next, a liability and coverage overview: whose insurance pays, and whether they've accepted fault yet. Then, case scenarios, where we'll work through real situations together, so bring your questions. Finally, the PD Specialist role: what you own on every file, from the first call to the final payment. By the end of today, you should be able to explain what a PD claim is, who pays for it, and what your job is in moving it forward. Quick question before we begin: of these four parts, which one do you think will be the hardest, and why?",
   "scenario": "A client calls and says: \"The other driver's insurance says they're still investigating, and my own insurance told me to wait. So who's paying for my car?\" Hold on to that question. By the end of today's four parts, you'll be able to answer it, and you'll know exactly who to call first."
  },
  {
   "page": 3,
   "title": "Overview: what property damage is",
   "notes": "Let's start with the basics: what is property damage? Property damage happens when something is destroyed or harmed, and because of that it loses value, stops working the way it should, or both. For our clients, that's usually the car after a crash, but it can be anything damaged in the incident, like a phone, a laptop or a child's car seat. Notice the two parts of the definition: value and functionality. A car can still run but be worth less because it now has an accident history. Or it can be fine on paper but unusable while it sits at the shop. Both of those are losses. In a personal injury case, the property damage claim is handled separately from the bodily injury claim, and it usually moves faster. But it still adds up: repair costs, the value the car loses even after it's fixed, or the cost to replace it if it's a total loss. So when someone says \"it's just the car,\" remember that for the client it's their transportation, their money and often how they get to work. Question for the room: besides the car itself, what else might a client lose because of the damage?",
   "scenario": "A client was rear-ended. Her car still drives, but the bumper is cracked, the trunk won't close, and the dealer says it's now worth less because it has an accident history. Her laptop on the back seat was also smashed. Using this definition, what has she lost in value, and what has she lost in functionality? Which of those losses belong in the property damage claim?"
  },
  {
   "page": 4,
   "title": "Overview: PD claims and the tort claim",
   "notes": "Now, where does a property damage claim come from? In a car accident case, it usually comes with what's called a tort claim. A tort is simply a legal wrong: someone was careless, and that carelessness hurt someone else. When a driver causes a crash, they can be responsible for two kinds of harm. First, the injuries: the medical bills, lost wages, pain and suffering. That's the bodily injury side. Second, the property: the car, and anything else damaged in the crash. That's our side. The property damage claim asks for the cost to repair the car, or to replace it if it can't be fixed, plus the value it lost because of the accident. In most cases, the at-fault driver's insurance company handles both claims. But here's the key point for your work: the property damage claim usually runs on its own track, often with a different adjuster, and it's usually settled long before the injury claim. So we never wait for the injury case to move the car forward. Question for the room: why do you think the insurance company would rather settle the car quickly, and separately?",
   "scenario": "A client was hit by a driver who ran a red light. She's in physical therapy for her neck, and her car is at the body shop. The at-fault driver's insurance calls and says: \"We'll deal with the car once we know more about her injuries.\" Is that how it should work? What do you say, and who on our team handles each part of her case?"
  },
  {
   "page": 5,
   "title": "Overview: the coverage types",
   "notes": "Property damage liability is just one piece of a car insurance policy. A policy is really a bundle of different coverages, and part of our job is spotting every one that could pay for our client's loss. Let's walk through them. First, liability coverage. It has two parts: property damage liability, which pays for damage the insured driver causes to other people's property, like our client's car, and bodily injury liability, which pays for the injuries they cause to other people. Next, collision coverage. This pays to fix or replace the policyholder's own car after a crash, no matter who caused it, minus their deductible. That's why we use our client's own collision when she's at fault, or when the other driver's insurance is slow or denies the claim. Then, comprehensive coverage, for damage that isn't a crash, like theft, fire, flood or a tree falling on the car. After that, uninsured and underinsured motorist coverage, for when the at-fault driver has no insurance, or not enough. Depending on the state and the policy, it can cover the car too. Finally, medical payments or PIP, which pays medical bills for the policyholder and passengers no matter who was at fault. That one belongs to the injury side, so we flag it to the BI team. Question for the room: if the other driver fled the scene, which coverage would you check first?",
   "scenario": "Your client was hit by a driver who carries only the state minimum liability limits, and the repair estimate is higher than those limits. Your client has collision coverage with a $500 deductible, plus uninsured/underinsured motorist coverage. Which coverages could pay for the car, in what order would you look at them, and what do you need to confirm before you rely on any of them?"
  },
  {
   "page": 6,
   "title": "Client Retention",
   "notes": "Here's why this work matters so much to the firm: client retention. For most clients, the car is the first thing they worry about after an accident. They can't get to work, they're paying for a rental or asking for rides, and the tow yard keeps calling. The injury claim can take months or even years, but the property damage claim is the first result the client actually sees from us. If we handle it quickly and clearly, the client trusts us, and that trust carries them through the longer injury case. If we're slow, or they can't reach us, or they hear about a problem before we tell them, they start wondering whether they hired the right firm, and some of them leave. So every call you return, every rental you set up and every update you give on the car does more than close a PD claim. It keeps the client with the firm. Question for the room: think of a time you dealt with an insurance claim or a service company. What made you trust them, or made you want to walk away?",
   "scenario": "A client calls, frustrated: \"It's been a week, my car is still at the tow yard, and nobody has told me anything. My cousin's lawyer got his car fixed in five days. Maybe I should switch firms.\" What do you say on this call, what do you do in the next hour, and how do you make sure she never has to make this call again?"
  },
  {
   "page": 7,
   "title": "Types of Property Damage",
   "notes": "There are two types of property damage, and you'll see both. First, real property. That's land and anything permanently attached to it: a house, a garage, a fence, a wall, a mailbox. In a car accident, this happens when a car leaves the road and hits someone's fence or storefront. It's usually not our client's loss, but it can come up, for example when our client's car is pushed into a fence. Next, personal property. That's anything a person owns that can be moved: the vehicle itself, and everything inside it, like a phone, a laptop, clothing, a child's car seat or work tools. For our clients the car is the biggest item, but don't forget what was inside it. Finally, how it's valued. Personal property is paid based on what it costs to repair it or, if it's destroyed, what it was worth at the time of the accident. That's often less than buying new, so receipts, photos and the item's age all matter. Question for the room: what personal items do you think clients forget to mention after a crash?",
   "scenario": "Your client's car was hit so hard it was pushed into a neighbor's front fence. Her car is totaled. Inside were her work laptop, a new car seat and her gym bag, and the fence and a mailbox were knocked down. Sort every item into real property or personal property. Which of these losses are part of our client's PD claim, and which belong to someone else?"
  },
  {
   "page": 8,
   "title": "Property Damage Liability and Coverage",
   "notes": "Now let's zoom in on the coverage that pays most of our claims: property damage liability. This is the part of the at-fault driver's policy that pays for the damage they caused to someone else's property. That's our client's car, but it can also be a fence, a building or a storefront the car hit. It pays to repair the property, or to reimburse its value if it can't be fixed. It also pays for cleanup after the crash, like removing a damaged tree or knocked-down signs. Here's the part to remember: it's called liability coverage because it only pays when its own driver is liable, meaning at fault. So before this coverage pays our client a single dollar, the insurance company has to accept that its driver caused the accident. That's why confirming liability is one of the first things we do on every file. Question for the room: if this coverage pays for everyone else's damage, whose damage does it never pay for?",
   "scenario": "A delivery van rear-ends your client at a stoplight, then swerves and knocks over a street sign. The van driver's insurance tells your client: \"We're still reviewing our driver's statement before we pay anything.\" Which coverage will pay for your client's car? Why hasn't it paid yet? And what can you do to move that decision along?"
  },
  {
   "page": 9,
   "title": "Property Damage Liability: the limits",
   "notes": "Let's stay on this coverage a moment longer, because it has two limits you need to know. First, it only pays for other people's property. It never pays to fix the at-fault driver's own car; for that, they'd use their own collision coverage. Second, it only pays up to the policy limit. Every policy has a maximum it will pay for property damage in one accident. If our client's car is worth more than that limit, or several cars were damaged in the same crash and they're all sharing it, the policy may not cover the full loss. When that happens, we look to the client's own coverages, like collision or underinsured motorist, and we tell the attorney right away. So on every file, don't just ask whether the other driver has insurance. Ask how much property damage coverage they have. Question for the room: why would it matter if three cars were damaged in the same accident?",
   "scenario": "A driver runs a red light and hits three cars, including your client's. The driver's policy has a property damage limit that looks fine for one car, but the other two cars are newer SUVs. What's the risk for your client, what do you ask the adjuster on your first call, and what backup coverage do you check on your client's own policy?"
  },
  {
   "page": 10,
   "title": "Items that go with the Bodily Injury claim",
   "notes": "Here's a rule that trips up a lot of new PD Specialists: some damaged items don't belong in the property damage claim at all. If an item was prescribed or recommended by a doctor, it goes with the bodily injury claim. Think prescription glasses, hearing aids, a brace, crutches or a wheelchair. Those items are tied to the person's health and treatment, so they're handled together with the injuries, not with the car. So when a client lists what was damaged, sort it as you go. First, items anyone could own, like a phone, a laptop or a car seat, stay in our PD claim. Next, anything that needed a doctor's prescription or recommendation gets flagged. Then, we send those items to the BI Case Manager with whatever proof the client has, like the receipt or the prescription, and we note in the file that we did. Finally, we tell the client which claim each item is in, so they don't think we forgot it. Question for the room: a client says her glasses broke in the crash. What's the one question you ask before you decide which claim they go in?",
   "scenario": "Your client lists what was damaged in the crash: her phone, her prescription glasses, her son's car seat, and her hearing aid, which flew off on impact. Sort each item: which ones stay in the PD claim, which ones go to the BI Case Manager, and what proof do you ask the client for?"
  },
  {
   "page": 11,
   "title": "Additional coverages to review",
   "notes": "So when does our client's own insurance come into play? Besides the other driver's liability coverage, there are three more coverages to review on every file. First, collision, which pays to fix the client's own car after a crash. Next, comprehensive, for damage that isn't a crash, like theft, hail, a flood or hitting a deer. Then, uninsured and underinsured motorist coverage. What it pays for depends on the client's policy: some cover the car, some only the rental, so we read the contract instead of guessing. Finally, when do we use these? In two situations: when our client caused the accident, because then no one else's liability coverage will pay, and when the other driver's property damage coverage isn't available, because they have no insurance, not enough, or the carrier denies the claim. That's why we ask for our client's declarations page on day one, even when the other driver is clearly at fault. Question for the room: why would we want the client's own coverage information even when the other driver is 100% at fault?",
   "scenario": "Your client was hit by a driver with no insurance. Her car needs $6,000 in repairs and she needs a rental while it's fixed. Her policy has collision with a $1,000 deductible and uninsured motorist coverage. Which coverage do you look at for the car, which for the rental, and what do you need to read in her policy before you tell her anything?"
  },
  {
   "page": 12,
   "title": "Types of Coverages (section title)",
   "notes": "Now we're moving into the coverages themselves. Earlier we saw that a car insurance policy is really a bundle of coverages. In this section, we'll take the most important ones one at a time: property damage liability, which pays when the other driver is at fault; collision and comprehensive, which protect our client's own car; and the others that can help, like uninsured motorist and rental coverage. For each one, ask yourself three questions: whose policy is it, what does it pay for, and what has to happen before it pays? Look at the car in this photo. If it were our client's, the answer to \"who pays\" could change completely depending on who caused the crash and what coverage everyone has. Quick check before we start: who can name the coverage that pays for someone else's car when you cause an accident?",
   "scenario": "The car in this photo hit the guardrail after another driver cut it off and drove away. There's no police report yet, and no one got the other driver's plate. Before we go through each coverage, make a guess: whose insurance could pay for this car? We'll come back to your answer at the end of this section."
  },
  {
   "page": 13,
   "title": "Property Damage Liability (the four boxes)",
   "notes": "Let's look at property damage liability more closely, the way the insurance company sees it. It's part of the at-fault driver's policy, and it pays for the damage their car causes to other people's property. First, what it covers: any property damaged in the crash, personal property like our client's car and what was in it, or real property like a fence or a building. Next, it also protects the at-fault driver if they're sued, because it can pay for their legal defense. That's why, when our attorney makes a demand, it's the insurance company that responds, not the driver. Then, the limit: every policy caps how much it will pay per accident. The slide talks to drivers choosing their own coverage, but for us the point is this: the other driver's limit is the most our client can collect from that policy. Finally, most states require drivers to carry it as part of their minimum insurance, but the minimum can be low, and some drivers don't carry it at all. Question for the room: if the at-fault driver has only the state minimum, what's the first thing you'd compare that limit to?",
   "scenario": "The at-fault driver has only the minimum property damage limit your state requires. Your client's car is a two-year-old SUV, and the body shop estimate is already close to that limit, before the rental and towing bills. What's your concern, who do you tell, and which of your client's own coverages do you check next?"
  },
  {
   "page": 14,
   "title": "Property Damage Liability (the declarations page)",
   "notes": "Here's what property damage liability looks like on a real declarations page, the summary page of a policy. Let's read it together. First, bodily injury liability: $250,000 each person and $500,000 each accident. That's the injury side, and it's the BI team's number. Next, property damage liability: $100,000 each accident. That's our number. It's the most this policy will pay for all the property damaged in one crash, not per car. Then, medical payments: here it says not included, so there's no MedPay on this policy. You'll often see these limits written in shorthand as 250/500/100. Finally, the takeaway from the slide: this coverage exists to protect the driver who causes the crash, but for us it's the pot of money our client's claim is paid from. So on every file, we get the at-fault driver's limits, write them in the file, and check them against the damage. Question for the room: using this page, if three cars were damaged in the same crash, how much is available for all three together?",
   "scenario": "The at-fault driver's declarations page shows 25/50/25. Your client's car is a total loss worth about $30,000, and a second car in the same crash has $12,000 in damage. What does 25/50/25 mean? Why might there not be enough for your client, and what do you do about the gap?"
  },
  {
   "page": 15,
   "title": "Collision / Comprehensive Coverage (the three boxes)",
   "notes": "Now let's switch to the coverages that protect our client's own car: collision and comprehensive. First, collision pays to repair or replace the client's car after a crash, no matter who was at fault. That includes hitting another car, a tree, a pole, a guardrail or any other object. Next, comprehensive pays for damage that isn't a crash: theft, vandalism, fire, hail, floods, falling objects or hitting an animal. Then, three things to know about both. They don't have a dollar limit the way liability does, but they never pay more than the car was worth before the accident. They only pay for the policyholder's own car, never for anyone else's, so they're not third-party liability coverage. And the client covers the deductible: it's taken out of what the insurance company pays, and the client pays that part to the shop. Finally, here's why this matters for us: when we use the client's own collision because the other side is slow or denies the claim, we then go after the at-fault carrier to get the client's deductible back. Question for the room: a deer runs into your client's car. Collision or comprehensive?",
   "scenario": "Your client's car was damaged in a hailstorm the same week another driver sideswiped it in a parking lot and drove off. She has collision with a $1,000 deductible and comprehensive with a $250 deductible. Which coverage handles each part of the damage, what will she pay out of pocket, and what do you tell her about getting any of that money back?"
  },
  {
   "page": 16,
   "title": "Collision / Comprehensive Coverage (the declarations page)",
   "notes": "Here's where to find these coverages on the client's own declarations page. First, look for collision and comprehensive listed for the specific vehicle that was damaged. Coverage is listed car by car, so if the client has two cars, make sure you're reading the right one. Next, find the deductible next to each one, for example $500 for collision and $250 for comprehensive. That's the amount the client covers if we use that coverage. Then, check for words like \"not included\" or \"declined.\" Some clients, especially with older or paid-off cars, carry only liability, which means there's no collision or comprehensive to fall back on. After that, look nearby for rental reimbursement and towing coverage, because they're usually listed in the same section. Finally, write all of it in the file on day one: which coverages the client has, the deductibles, and the policy number. Question for the room: why would a client with a car loan almost always have collision and comprehensive?",
   "scenario": "Your client's declarations page shows liability only on her 2012 sedan, and full coverage with a $500 collision deductible on her 2021 SUV. The damaged car is the 2012 sedan, and the at-fault driver's insurance has just denied liability. What coverage does she have for this car, what options are left, and who do you bring in?"
  },
  {
   "page": 17,
   "title": "Collision Coverage",
   "notes": "Let's look at collision on its own. Collision pays for damage to the policyholder's own car when it hits something: another vehicle, a tree, a guardrail, a fence or a pole. First, it applies no matter who was at fault. So even if our client caused the crash, or fault hasn't been decided yet, collision can get her car fixed. Next, it's usually required when the car has a loan or a lease, because the lender wants its investment protected. That means clients with financed cars almost always have it, and when the car is repaired or totaled, the lender may be named on the check. Then, remember the deductible: the client pays that part, and if the other driver was at fault, we work to get it back. Finally, using collision is the client's choice. We explain the option, the deductible and the timing, and let them decide. Question for the room: when would a client want to use her own collision even though the other driver was clearly at fault?",
   "scenario": "Your client's financed car was hit by a driver whose insurance says it needs three more weeks to decide liability. Her car is drivable, but the trunk won't latch and she's worried about rain getting in. She has collision with a $500 deductible. Walk her through her options: wait for the other insurance company, or use her collision now. What does each option cost her, and what happens to the deductible later?"
  },
  {
   "page": 18,
   "title": "Comprehensive Coverage",
   "notes": "Now comprehensive. Comprehensive pays for damage to the policyholder's car that doesn't come from a crash. First, the common causes: theft, vandalism, fire, hail, floods, storms, falling objects like a tree branch, and hitting an animal such as a deer. Next, the word \"broader\": this coverage protects the car even when it's parked and nobody's driving it. Then, like collision, it's usually required when the car is financed or leased, so most clients with a car loan will have it, with its own deductible. Finally, two traps to watch for. People assume hitting a deer is a collision, but most policies treat it as comprehensive, which often means a lower deductible for the client. And if something is stolen out of the car, like a laptop, that's usually a homeowner's or renter's insurance issue, not auto. Question for the room: a client's car is broken into and the window is smashed. Which coverage pays for the window?",
   "scenario": "A client's parked car was damaged overnight: a storm knocked a tree branch onto the hood, and while she was dealing with that, someone broke in and stole her work tablet. She has comprehensive with a $250 deductible. Which parts of this loss does comprehensive handle, what might not be covered by her auto policy at all, and what do you tell her to check?"
  },
  {
   "page": 19,
   "title": "Remember! Rule 1: the responsible party's insurance",
   "notes": "Now the \"Remember\" rules. Together they're the decision path you'll follow on every file, so let's take them one at a time. Rule one: the at-fault driver's insurance should pay for our client's property damage, as long as that driver has the right coverage, meaning property damage liability, and the insurance company accepts that its driver was at fault. That's always our first stop. So on day one, we get the other driver's insurance company, policy number and claim number, we confirm the policy was active on the date of the accident, and we ask whether liability has been accepted. Only when that path is blocked do we move to the next rule. Question for the room: what are all the ways this first path can be blocked?",
   "scenario": "Your client was rear-ended at a red light. The other driver's insurance card from the scene shows property damage liability, but when you call the insurance company, the representative says the policy was cancelled two weeks before the accident for non-payment. What does that mean for rule one, what do you document, and where do you go next?"
  },
  {
   "page": 20,
   "title": "Remember! Rule 2: using the client's own coverage (1P)",
   "notes": "Rule two: if we can't get coverage from the third party, meaning the at-fault driver's insurance, but the client has coverage on their own policy, the first party, we present that option to the client. It's the client's decision, not ours. We explain it clearly: their own collision or other coverage can fix the car now, but they'll have to pay the deductible they chose when they bought the policy. We also tell them what happens next: if the other driver was at fault, their insurance company can try to recover what it paid from the other side, and we work to get their deductible back too. And we're honest that the recovery isn't guaranteed and can take time. Then we note in the file what we offered, what the client chose, and when. Question for the room: why is it important that the client, not us, makes this choice, and that we write it down?",
   "scenario": "The at-fault driver's insurance denied the claim, saying their driver wasn't at fault. Your client's own policy has collision with a $1,000 deductible, and she tells you: \"I can't afford a thousand dollars right now, and I didn't cause this.\" How do you explain her options, what do you say about the deductible, and what do you write in the file?"
  },
  {
   "page": 21,
   "title": "Remember! Rule 3: no coverage anywhere",
   "notes": "Rule three: if there's no coverage anywhere, not on the at-fault driver's policy and not on the client's own, we report it to the attorney for further handling. That's not the end of the claim, it's a handoff. The attorney decides what happens next, for example whether to pursue the at-fault driver personally. Our job is to make that handoff complete. First, confirm there's really no coverage: we've checked the other driver's policy, the client's own collision and uninsured motorist coverage, and any other policy that might apply. Next, put it in writing: a short summary of what we checked, who we spoke to, the dates, claim numbers and the answers we got. Then, tell the client honestly that the attorney is reviewing their options, without promising an outcome. Finally, keep working what we can in the meantime, like getting the car out of storage so the fees stop piling up. Question for the room: what should be in your report so the attorney doesn't have to call you back with questions?",
   "scenario": "An uninsured driver hit your client, who carries liability only: no collision and no uninsured motorist property damage coverage. Her car is at a tow yard charging daily storage, and she asks you, \"So I just lose my car?\" What do you tell her today, what goes in your report to the attorney, and what can you still do about the storage bill while the attorney reviews the case?"
  },
  {
   "page": 22,
   "title": "Remember! Rule 4: liability disputes",
   "notes": "Rule four is about liability disputes, when the other driver's insurance says its driver wasn't at fault, or blames our client. When a dispute can't be settled by negotiation, the case may have to go through litigation, meaning a lawsuit. But here's the important part: whether to file is the attorney's decision, not ours, and we never tell a client their case is going to court. First, gather the evidence that could change the insurance company's mind: the police report, photos, witness names and any statements. Next, send it to the adjuster and ask for the liability decision in writing. Then, if the dispute stands, report it to the attorney with that file. Finally, while the attorney decides, remind the client about their own coverage options, so they're not stuck without a car. If you speak to the client, say something like: \"The other insurance company is disputing fault. Our attorney is reviewing the next steps and will talk with you about them.\" Question for the room: why shouldn't a PD Specialist tell a client \"we'll have to sue\"?",
   "scenario": "The other driver's insurance says your client ran a stop sign. Your client swears the other driver did, and a witness from the scene agrees with her. The adjuster won't budge. The client asks you, \"So are we going to court?\" What do you say, what do you send the adjuster, and what goes to the attorney?"
  },
  {
   "page": 23,
   "title": "Remember! Affidavit of No Additional Insurance",
   "notes": "One more tool from the \"Remember\" rules: the Affidavit of No Additional Insurance. When the at-fault driver's policy isn't enough to cover the damage, we can ask the at-fault party to sign a sworn statement saying whether they have any other insurance that could apply. Why does that matter? Because there may be another source of money we don't know about. For example, the driver was working and their employer's policy covers them, the car belongs to someone else who has their own policy, or the driver has an umbrella policy. First, we request the affidavit, usually through the at-fault driver's insurance company or through the attorney. Next, we track it so it doesn't get lost. Then, when it comes back, we read it carefully: any other policy listed is a new lead to follow up. Finally, it goes in the file and the attorney gets a copy, because it affects how much the client can recover. Question for the room: what kinds of other insurance could an at-fault driver have that would pay for our client's car?",
   "scenario": "The at-fault driver's property damage limit is lower than your client's repair estimate. The police report shows the driver was making deliveries for a local restaurant at the time of the crash, in a car registered to his brother. What other policies could apply, what do you want the affidavit to answer, and who do you tell before you request it?"
  },
  {
   "page": 24,
   "title": "Sample Scenarios: if the client is at fault",
   "notes": "Now let's apply the rules to sample scenarios, starting with the one clients find hardest to hear: when our client is at fault. First, confirm fault before you accept it. Talk to the other driver's insurance company and find out how they see it. Fault isn't always all or nothing: if the other driver was partly to blame, their insurance may pay part of our client's damage, depending on the state. Next, if the other side won't pay, check our client's own policy. Collision is the coverage that pays for a crash, minus the deductible. Comprehensive only helps if some of the damage didn't come from the crash, like a break-in afterward. Then, remind the client to report the accident to her own insurance company, because the other driver will be making a claim against her policy. Finally, if there's no coverage on either side, it goes to the attorney. Throughout, stay kind and factual: clients who caused an accident are often embarrassed and worried, and they need clear options, not judgment. Question for the room: how would you gently explain to a client that the other driver's insurance won't pay for her car?",
   "scenario": "Your client turned left in front of an oncoming car and admits she didn't see it. The other driver's insurance says she's 100% at fault. Her car needs $4,500 in repairs; she has collision with a $500 deductible and no rental coverage. She asks, \"Why can't their insurance pay? My car is the one that got wrecked.\" How do you explain it, what are her options for the car and for getting around, and what do you remind her to do with her own insurance company?"
  },
  {
   "page": 25,
   "title": "Sample Scenarios: client at fault (next steps)",
   "notes": "Let's finish the at-fault path. Once we've confirmed our client is at fault and the other side won't pay, the next step is to file a claim with our client's own insurance company, under her collision coverage, if she has it. First, we get her policy number, confirm collision is on the damaged car, and open the claim. We explain the deductible before we file, so there are no surprises. Next, if her policy has no collision, or neither driver has coverage that applies, we tell the handling attorney right away, with what we checked. Then, we keep looking. Sometimes there's another policy that can help: a second policy in the household, or the owner's policy if she was driving someone else's car. Finally, we document every coverage we checked and every answer we got, so the attorney can see at a glance that nothing was missed. Question for the room: our client was driving her friend's car when she caused the crash. Whose collision coverage would you check first?",
   "scenario": "Your client admits she rear-ended another car. She thinks she doesn't have collision coverage, but she isn't sure, and she says her husband \"has really good insurance.\" What exactly do you check, in what order, and what do you do if neither policy covers her car?"
  },
  {
   "page": 26,
   "title": "Examples of Coverage Issues",
   "notes": "These are the four coverage problems you'll run into most, and each one can stop a claim in its tracks. First, multiple vehicles and a small policy. Say the at-fault driver has a $10,000 property damage limit and hits three cars. That $10,000 is all the policy will pay for all of them together, and anything above it is the at-fault driver's personal responsibility, which is much harder to collect. Next, an inactive policy: one that was cancelled, expired or not renewed before the accident. The insurance card may look fine, but if the policy wasn't active on the date of the accident, there's no coverage. Then, an unlisted driver: someone driving a car whose policy doesn't list them. Many policies still cover a driver who had the owner's permission, but some exclude drivers who live in the household and aren't listed, so we check. Finally, rideshare and delivery drivers, like Uber. A personal policy often won't cover a driver who was working, and the rideshare company's insurance may apply instead, depending on whether the app was on and whether they had a passenger. Question for the room: which of these four could you catch on your very first call to the adjuster, and how?",
   "scenario": "The at-fault driver was working for a rideshare app, had just dropped off a passenger, and was driving his cousin's car, which he isn't listed on. His cousin's insurance says the policy lapsed last month. List every coverage problem in this claim, and for each one, what you ask and who you ask."
  },
  {
   "page": 27,
   "title": "Liability Accepted, Coverage Denied",
   "notes": "Now a situation that confuses a lot of clients: liability accepted, coverage denied. It sounds like a contradiction, so let's break it down. First, \"liability accepted\" means the insurance company agrees its side caused the accident. Next, \"coverage denied\" means that even so, the policy won't pay, because this driver or this situation isn't covered. The most common reason is an unlisted or excluded driver, but it can also be a lapsed policy or a car being used for business. Then, what we do: ask the adjuster for the denial in writing, with the exact reason and the policy language, and add it to the file. A denial over the phone isn't enough. Finally, we move to the next coverage path, starting with the client's own policy, and we tell the client in plain words: \"They agree their driver caused it, but their policy won't pay for this driver, so here are your options.\" Question for the room: why is it so important to get the coverage denial in writing?",
   "scenario": "The adjuster tells you: \"Our insured's nephew was driving, and he's an excluded driver on the policy. We agree he caused the accident, but we won't be paying.\" Your client has collision with a $500 deductible and uninsured motorist coverage. What do you ask the adjuster for before you hang up, how do you explain this to your client, and which of her coverages do you look at next?"
  },
  {
   "page": 28,
   "title": "Liability Accepted, Coverage Denied (next steps)",
   "notes": "So what do we do when liability is accepted but coverage is denied? The same path as before. First, file a claim with our client's own insurance company. Depending on her policy, that's her collision coverage, and in many states her uninsured motorist coverage too, because a driver whose insurance won't pay can be treated like an uninsured driver. We explain the deductible and let her decide. Next, if she has no coverage that applies, we tell the handling attorney, with the written denial, the at-fault driver's details and what we checked. Then, we keep the claim moving while the attorney reviews it: get the car out of storage, and keep the client updated. Finally, we note the date and reason of the denial in the file, because if the denial is ever reversed or challenged, that date matters. Question for the room: why might the client's uninsured motorist coverage apply here, even though the other driver technically has insurance?",
   "scenario": "The other insurance company denied coverage because its driver wasn't listed. Your client has no collision coverage, but she does have uninsured motorist property damage with a $250 deductible. What do you file, what documents do you need from the other insurance company, and what do you tell your client about how long this might take?"
  },
  {
   "page": 29,
   "title": "No One Cited at Fault in the Police Report",
   "notes": "Next scenario: the police report doesn't cite anyone as at fault. Without a ticket or a clear finding in the report, each insurance company decides liability mostly from what its own driver tells it. And no surprise: the other driver usually says it wasn't their fault. So in most of these cases, the other insurance company denies the claim, at least at first. First, don't accept that first answer as final. Next, find out exactly what their driver said, and ask the adjuster what evidence they relied on. Then, get our client's full account while it's fresh, and look for anything that supports it: photos, where each car was damaged, witnesses and cameras. Finally, prepare the client: this kind of claim often takes longer, and she may need to use her own coverage in the meantime. Question for the room: if two drivers tell opposite stories, what kind of evidence can break the tie?",
   "scenario": "Two cars collided in an intersection. The police report lists no violations and no one at fault. The other driver told his insurance he had a green light; your client says she did. The adjuster says: \"It's his word against hers, so we're denying the claim.\" What do you ask the adjuster, what do you ask your client, and where could you find evidence that settles who had the light?"
  },
  {
   "page": 30,
   "title": "No One Cited at Fault (find fault and coverage first)",
   "notes": "So when the report is silent, our job is to work out who's at fault ourselves, and to learn what coverage everyone has, before we pick a path. First, request the full police report, not just the information-exchange slip from the scene, and read the officer's narrative and diagram. Next, get both drivers' insurance information and confirm each policy was active on the date of the accident. Then, ask each insurance company for its liability decision and the reason behind it. Finally, put the pieces together: if the evidence points to the other driver, we push their insurance with it; if it's unclear, we look at our client's own coverage so she isn't stuck without a car while fault is sorted out. Question for the room: what's in the full police report that isn't on the slip drivers get at the scene, and why does it matter here?",
   "scenario": "Your client was sideswiped while changing lanes on the highway. The police report lists both drivers but no fault, and your client doesn't know which insurance company the other driver has. Walk through your first three calls: who do you call, what do you ask each one, and what do you write in the file after each call?"
  },
  {
   "page": 31,
   "title": "No One Cited at Fault (the evidence, then which insurance to file with)",
   "notes": "Here's what to do when the police report is silent. First, review the report carefully. Officers often don't assign fault when the evidence isn't clear at the scene, but the report may still include statements, witness names or details that point to who was at fault. Next, gather more evidence: witness statements, traffic or business camera footage, and photos of the scene and of where each car was damaged. The damage itself often tells the story: if one car is hit on the side and the other on its front, that points to who hit whom. Then, once we know who's at fault, we check that driver's coverage limit. If the limit is enough to cover the damage, we file with the at-fault driver's insurance. If it isn't enough, we file with our client's own insurance, and her insurance company can then go after the at-fault side to recover what it paid. That's called subrogation. Finally, we keep the client informed at every step, because these claims take longer. Question for the room: what does the location of the damage on each car tell you about who hit whom?",
   "scenario": "The police report assigns no fault, but a gas station on the corner has a camera facing the intersection. The other driver's policy has a $10,000 property damage limit, and your client's repair estimate is $18,000. What do you do about the camera footage, and how quickly? Which insurance do you file with, and what will subrogation do for your client?"
  },
  {
   "page": 32,
   "title": "Multiple Vehicles Involved",
   "notes": "Multi-vehicle accidents are where liability gets complicated. Here's the process. First, gather information on every vehicle: each driver's insurance, their statements, witness accounts and photos of every car's damage. Next, get the police report. It may help determine fault, but in a chain-reaction crash it often says the accident is under investigation. Then, understand how fault gets split. More than one driver can be at fault, and each insurance company investigates and decides its own driver's share. In most states, damages are split by percentage of fault, which is called comparative negligence. In a few states, contributory negligence applies, where a driver who is even slightly at fault may recover nothing. Finally, the rule on the slide: if our client has no collision coverage and none of the insurance companies accepts liability, there's no insurance claim we can file right now. That doesn't mean we stop; it means the file goes to the attorney with everything we gathered. Question for the room: in a three-car pile-up, why might each insurance company point at a different driver?",
   "scenario": "Your client was the middle car in a three-car chain reaction on the freeway. The front driver's insurance blames the rear driver; the rear driver's insurance says your client stopped too suddenly. Your client has no collision coverage, and the police report says \"under investigation.\" What do you collect from each insurance company, what do you tell your client, and when does this go to the attorney?"
  },
  {
   "page": 33,
   "title": "Partial Liability",
   "notes": "Partial liability means more than one driver is responsible for the accident, but not equally. Think of it as a percentage. First, how it's decided: each driver's share depends on how serious their mistake was. For example, a driver who ran a red light carries more of the blame than a driver who was going a little too fast for the conditions. Next, what it means for money: if our client is found 20% at fault, the other insurance company usually pays 80% of her damage, not 100%. That's comparative negligence, and it's how most states work. Then, the exception: in a few states, contributory negligence applies, where being even slightly at fault can block recovery. That's a question for the attorney, never a guess. Finally, the percentages are negotiable. The first split the adjuster offers isn't always right, so we gather evidence and let the attorney weigh in before the client accepts it. Question for the room: if the damage is $10,000 and our client is found 30% at fault, how much should the other insurance company pay?",
   "scenario": "The other driver ran a stop sign, but your client was looking at her phone and didn't brake. The other insurance company offers to pay 50% of her $8,000 repair bill, saying she was equally at fault. What do you ask about how they reached 50%, what evidence could change the split, and who decides whether the client accepts it?"
  },
  {
   "page": 34,
   "title": "Partial Liability: setting the client's expectations",
   "notes": "When liability is shared, setting the client's expectations early is part of the job. If we go after the other driver's insurance, the defense side, it will only pay its driver's share. First, explain the split in plain numbers. If she's 30% at fault on a $10,000 repair, the other insurance pays $7,000, and the remaining $3,000 has to come from somewhere else. Next, explain where that gap can come from: her own collision coverage, minus her deductible, or her own pocket if she has no collision. Then, cover the rental: the other insurance usually pays only its share of the rental too, so she may owe part of it. Finally, put it in writing after the call, so there are no surprises later. The worst outcome is a client who expects 100% and gets 70% without warning. Question for the room: how would you say this to a client who is sure the accident wasn't her fault at all?",
   "scenario": "Liability is split 70/30 in your client's favor. Her repair estimate is $6,000 and her rental so far is $900. She has collision with a $1,000 deductible. She says, \"Great, so they're paying for everything, right?\" How do you explain what the other insurance will pay, what she might owe, and her options to cover the rest?"
  },
  {
   "page": 35,
   "title": "Partial Liability: going after their insurance",
   "notes": "Even when fault is shared, we still strongly recommend going after the other driver's insurance for their share. That's how we keep the client's own costs as low as possible. First, file with the at-fault driver's insurance and let them assess each driver's share of fault. Their share is money the client would otherwise pay herself or claim on her own policy. Next, use the client's own coverage to fill the gap if it makes sense: collision for her share of the car, minus the deductible. Then, if the other driver's coverage isn't enough to pay even their share, check the client's underinsured or uninsured motorist coverage for the rest. Finally, remember that medical bills belong to the injury side of the case, so anything about treatment goes to the BI Case Manager, not into the PD claim. Question for the room: why go after the other insurance at all, if the client has collision coverage and could just use that?",
   "scenario": "The other driver is found 60% at fault. Your client has collision with a $1,000 deductible and asks: \"Can't I just use my own insurance and be done with it?\" What does she gain by also claiming the other driver's 60% share, what could she lose by using only her own collision, and how do you help her decide?"
  },
  {
   "page": 36,
   "title": "Deductibles",
   "notes": "Let's be clear on deductibles, because clients ask about them on almost every file. A deductible is the part of a claim the policyholder pays themselves before their own insurance pays the rest. In practice, the insurance company usually subtracts it from the payment, and the client pays that amount to the shop. First, the trade-off: a higher deductible makes the policy cheaper, but it means paying more out of pocket when there's a claim. Next, when it applies: deductibles apply when the client uses her own coverage, like collision or comprehensive. When the at-fault driver's insurance pays under its liability coverage, there's no deductible for our client. Then, getting it back: if the client uses her own coverage and the other driver was at fault, her insurance company can recover from the other side, and the deductible is usually part of what we work to get back. Finally, always tell the client the deductible amount before she decides which coverage to use. Question for the room: why does a client with a $2,000 deductible care so much more about the other driver's insurance paying?",
   "scenario": "Your client's repair estimate is $1,800. Her collision deductible is $2,000, and the other driver's insurance is still investigating liability. She asks whether she should just file with her own insurance to speed things up. What do you tell her, and why?"
  },
  {
   "page": 37,
   "title": "Partial Liability: the client conversation",
   "notes": "Let's close out partial liability with how you actually say this to a client, because the recommendation on the slide only works if the client understands it. First, lead with the benefit: \"Even though they're saying you share some of the fault, their insurance still owes their share, and going after it keeps money in your pocket.\" Next, explain what it saves her: when the other insurance pays its share, she doesn't pay a deductible on that part and doesn't have to put the whole claim on her own policy. Then, be honest about the gap: her share still has to come from her own coverage or her own pocket, and we'll give her the exact numbers once we have them. Finally, confirm her decision and write it down. If she wants to use only her own coverage instead, that's her right, and we note that we explained both options. Question for the room: what words would you avoid on this call, and why?",
   "scenario": "Role-play this call in pairs. The client says: \"If I'm partly at fault, I don't want to fight with anyone. Let's just use my insurance.\" She has a $1,000 deductible, and the other driver is 60% at fault. The PD Specialist's goal: explain her options clearly, without pressuring her, and end with a clear decision you can document."
  },
  {
   "page": 38,
   "title": "Wrongful Denial: challenging the decision",
   "notes": "Now, wrongful denial. Sometimes the other insurance company denies liability, or puts most of the fault on our client, and she strongly believes she wasn't responsible. She has the right to challenge that decision, and when she wants to, the case goes to the assigned attorney. First, listen to her side and write down exactly why she believes the decision is wrong: what happened, what the other driver did, and who saw it. Next, gather what supports her: the police report, photos, witness names, any camera footage, and the adjuster's denial in writing. Then, refer the case to the attorney with that package, so they can decide how to challenge it. Finally, tell the client what happens next in plain words, without promising a result: \"You have the right to challenge this. I've sent everything to your attorney, who will review it and talk with you about the next steps.\" Question for the room: what's the difference between disagreeing with a denial and being able to show it's wrong?",
   "scenario": "The other insurance company says your client is 100% at fault for a lane-change crash. She's upset and says the other driver sped up to cut her off, and her dashcam may have caught it. What do you ask her for today, what goes to the attorney, and what do you tell her about what happens next?"
  },
  {
   "page": 39,
   "title": "Wrongful Denial: litigation takes time",
   "notes": "When a liability dispute heads toward litigation, it can take a long time, sometimes months or longer, and the client needs to hear that from us early. First, prepare her for the timeline: a lawsuit, if the attorney decides to file one, moves slowly, and her car can't sit in a shop or a tow yard waiting for it. Next, that's why we offer the other option: using her own insurance, usually her collision coverage, to get the car repaired now. It's faster, and it doesn't stop the attorney from going after the other side. Then, explain the trade-off: she'll pay her deductible, and if the case succeeds, her insurance company can recover what it paid, and we work to get her deductible back. Finally, let her decide, and document the conversation and her choice. Question for the room: why is it risky for a client to wait for the lawsuit before fixing her car?",
   "scenario": "The attorney is reviewing a disputed liability claim, and the client's car has been at the body shop for three weeks waiting for someone to authorize repairs. The shop just started charging storage. The client has collision with a $500 deductible. What do you explain to her today, what are her options, and what do you document?"
  },
  {
   "page": 40,
   "title": "Wrongful Denial: setting expectations about subrogation",
   "notes": "If the client uses her own insurance, she also needs to understand subrogation, so let's make it simple. Subrogation is when her insurance company, after paying for her car, goes after the at-fault driver's insurance to get its money back. First, what it means for her: her car gets fixed now, through her own coverage, and the fight over who pays happens between the two insurance companies. Next, the deductible: if the subrogation succeeds, her deductible is usually part of what's recovered and returned to her. Then, the timing: it can take months, and it's separate from her claim, so she shouldn't expect that money back quickly. Finally, the honest part: recovery isn't guaranteed. If the other side is found not at fault, or has no coverage, she may not get the deductible back. We tell her all of this up front and note it in the file, so she's never surprised. Question for the room: how would you explain subrogation to a client in one sentence?",
   "scenario": "Six months ago, your client used her collision coverage after a disputed accident and paid a $1,000 deductible. She calls: \"My insurance fixed the car ages ago. Where's my thousand dollars? You said I'd get it back!\" What do you check, who do you call, and how do you respond to her, especially about what she was told at the start?"
  },
  {
   "page": 41,
   "title": "People We Work With",
   "notes": "No PD claim is handled alone. Here are the people you'll work with on every file. First, the client: the person whose car, and daily life, we're helping put back together. Next, the intake specialist, who signs up the client and gathers the first facts. Their notes are your starting point, but always verify them. Then, the handling attorney, who makes the legal decisions, like disputes, denials and anything that may go to court. After that, the people outside the firm: vehicle appraisers, who inspect the car and estimate the damage; body shops, which repair it and often find more damage once they take it apart; and adjusters, who work for the insurance companies and decide what gets paid. Finally, remember this: your job is to keep all of them moving in the same direction. A claim stalls when one of them is waiting on another and no one is following up. Question for the room: which of these people do you think you'll talk to most often, and why?",
   "scenario": "It's Tuesday. The body shop says it's waiting for the appraiser, the appraiser says he's waiting for the adjuster to assign the inspection, and the adjuster hasn't returned your call since Friday. The client's rental ends Thursday. Who do you call first, what do you ask each person, and how do you keep the client informed?"
  },
  {
   "page": 42,
   "title": "Types of Adjusters: the Property Damage Adjuster",
   "notes": "Insurance companies often split a claim between different adjusters, and knowing who does what saves you a lot of wasted calls. First, the property damage adjuster. This is the person who handles the overall property damage claim: they confirm the coverage, decide what's covered, arrange the inspection, review the estimates and negotiate the settlement for the damage. When you have a question about who's paying and how much, this is your person. Next, keep in mind they're not neutral: they work for the insurance company, so we're polite and professional, but we verify what they tell us and get important decisions in writing. Then, get their direct contact information on the first call: name, phone, email, claim number, and who covers for them when they're out. Finally, note every conversation in the file, with the date and what was agreed. Question for the room: what should you always ask for before you hang up with an adjuster?",
   "scenario": "You call the insurance company about your client's claim and get routed to three different people in 20 minutes: a claims representative, a property damage adjuster and an appraiser. Each one gives you a different answer about when the car will be inspected. What do you ask each of them, whose answer do you rely on, and what do you put in writing?"
  },
  {
   "page": 43,
   "title": "Types of Adjusters: the Auto Damage Adjuster",
   "notes": "Next, the auto damage adjuster. Some insurance companies have a separate adjuster who handles the car once the claim is set up. First, what they do: they monitor the repairs, approve supplements when the shop finds more damage, and manage the rental, including how long it's authorized and at what daily rate. Next, why that matters for us: this adjuster often sets the rental end date, and if repairs run long, the client's rental can end while the car is still in the shop. Then, our job: check the repair progress with the shop, and before the rental end date, call the adjuster to confirm it will be extended. Finally, write down every authorization: the rental dates, the daily rate and the approval for any supplement. Question for the room: what happens to the client if the rental ends two days before the car is ready, and whose job was it to see that coming?",
   "scenario": "Your client's car is at the shop, and the rental is authorized through Friday. On Wednesday, the shop calls: they found hidden damage and need a supplement approved, which will add a week to the repair. What do you do today, who do you call first, and what do you tell the client about her rental?"
  },
  {
   "page": 44,
   "title": "Types of Adjusters: the Total Loss Adjuster",
   "notes": "And the total loss adjuster. When a car is too damaged to be worth repairing, the claim usually moves to this adjuster. First, what they do: they confirm the car is a total loss, get a valuation of what it was worth right before the accident, which is called the actual cash value, and calculate the payout. Next, how that payout is built: the car's value, often plus sales tax and fees depending on the state, minus any deductible if the client is using her own coverage. If there's a loan, the lender is paid first. Then, our job: we check the valuation carefully, because it's often lower than it should be. Are the comparable cars really comparable? Were the options, mileage and condition right? Finally, we never let the client accept or sign anything until we've reviewed the numbers and the attorney has approved the release. We'll go much deeper into total losses later in the week. Question for the room: why might a valuation come in lower than what the client thinks the car was worth?",
   "scenario": "The total loss adjuster offers your client $14,200 for her car. She owes $16,000 on her loan, and she found three similar cars for sale nearby for about $17,500. She's upset and asks if she has to take the offer. What do you review in the valuation, what do you ask the adjuster for, and what do you tell her about the loan?"
  },
  {
   "page": 45,
   "title": "The PD Specialist Role: Core Values",
   "notes": "Now let's talk about you, the PD Specialist, and the four core values behind the role. First, sense of urgency: every day a claim sits, the client pays for it in storage fees, rental costs and stress. Next, fanatical attention to detail: one wrong VIN, one missed date or one wrong number can delay a claim for weeks. Then, empathy: our clients are going through something stressful, and how we treat them matters as much as what we do. Finally, resolution driven: our job isn't just to work the file, it's to finish it, with the client made whole. We'll take each one in turn. As we go, think about which of these comes naturally to you, and which one you'll have to work on. Question for the room: which of these four values do you think clients notice first?",
   "scenario": "In one morning, you get three calls: a client whose storage fees are piling up, a body shop asking you to double-check a VIN that doesn't match the title, and a client in tears because she can't get to work. Match each call to a core value. Which do you handle first, and how does each value shape what you do?"
  },
  {
   "page": 46,
   "title": "The PD Specialist Role: trust under stress",
   "notes": "Let's start with what the client is carrying. After an accident, our client is under real emotional and mental strain: she may be hurt, she's without her car, and she may be dealing with insurance companies for the first time. First, why trust matters: a client who trusts us answers our calls, sends documents quickly and follows our advice. A client who doesn't trust us goes quiet, the claim slows down, and in the worst case, she ends our services. Next, how we build trust from the first call: we answer promptly, we explain what happens next in plain words, and we do what we said we'd do, when we said we'd do it. Then, speed is part of caring: nothing tells a stressed client we're on her side more than a problem solved today instead of next week. Finally, if trust slips, we fix it fast: call her back, acknowledge the frustration, and give her a specific next step and date. Question for the room: what's one thing you can do on a first call that makes a stressed client trust you?",
   "scenario": "A new client is short with you on the first call: \"The last law firm I used never called me back. Why should this be any different?\" She hasn't sent her insurance card or photos yet. How do you respond, what do you promise her, and what do you do in the next 24 hours to earn her trust?"
  },
  {
   "page": 47,
   "title": "The PD Specialist Role: why the car can't wait",
   "notes": "Here's the reality in the United States: for most people, a car isn't a luxury. It's how they get to work, take their kids to school and get to their medical appointments. So when the car is gone, the client's whole routine falls apart. First, put yourself in her position: every day without a car costs her time, money and stress. That's the empathy piece. Next, turn that understanding into action: move quickly on the rental, the tow yard and the adjuster. Then, keep her updated even when there's no news, because silence feels like nobody is working on it. Finally, understand what's at stake for the firm: if the car isn't handled promptly, the client can lose confidence in us and end the firm's representation, and with it, the injury case. Question for the room: what's the first thing a client needs when she has no car, and how fast can you get it for her?",
   "scenario": "Your client is a home health aide who drives to four patients a day. Her car was totaled on Monday, and it's now Thursday. The other insurance company hasn't accepted liability, she has no rental coverage, and her employer says she'll lose her shifts next week without a car. What can you do this week to get her back on the road, and what do you tell her today?"
  },
  {
   "page": 48,
   "title": "Fanatical Attention to Detail",
   "notes": "Fanatical attention to detail sounds dramatic, but in this role small mistakes cost real time and money. First, the details that matter most: the VIN, the claim numbers, the policy numbers, the date of the accident, names spelled correctly, and every dollar amount. Next, why: one wrong digit in a VIN can produce a valuation for the wrong car, and a wrong date of accident can make an insurance company say the policy wasn't active. Each of those mistakes can add weeks to the claim. Then, how to protect against it: verify every fact against a document, like the registration, the title, the police report or the declarations page, instead of relying on memory or intake notes. Finally, document everything the same day: who you spoke to, what was agreed, and what happens next. If it's not in the file, it didn't happen. Question for the room: where do you think the most common data mistakes come from?",
   "scenario": "You're reviewing a new file. The intake notes list a VIN ending in 5832, the tow invoice shows one ending in 5823, and the insurance card shows a different model year than the registration. The adjuster is waiting for your information to start the claim. What do you check, in what order, and which document do you trust for each fact?"
  },
  {
   "page": 49,
   "title": "Resolution Driven",
   "notes": "And the last value: resolution driven. Everything we've covered today points to one goal: getting the claim resolved, and the client made whole, as promptly as possible, whatever challenges come up. First, challenges will come up: denials, low offers, missing documents, adjusters who don't call back. Being resolution driven means each one gets a next step, not a pause. Next, always know what's blocking the file and who needs to act, whether it's you, the client, the shop, the adjuster or the attorney. Then, follow up on schedule: if you're waiting on someone, set a date to check back, and keep it. Finally, measure yourself by outcomes: is the car fixed or paid for, is the rental covered, and is the client satisfied? That's what success looks like in this role. Question for the room: what's one habit you'll use to make sure none of your files sits still?",
   "scenario": "You inherit five files from a colleague who left. Each one has been untouched for two weeks: one is waiting on a police report, one on a valuation, one on a client signature, one on a denial letter, and one just says \"called adjuster, no answer.\" How do you decide which to work first, and what's the next step on each?"
  },
  {
   "page": 50,
   "title": "Closing: thank you, see you tomorrow",
   "notes": "That's it for Day 1. Thank you, everyone! Let's recap what we covered. First, what property damage is, and how the PD claim sits next to the injury claim. Next, the coverages that can pay: property damage liability on the at-fault side, and collision, comprehensive and uninsured motorist coverage on the client's own policy. Then, the sample scenarios and the decision path: the at-fault driver's insurance first, the client's own coverage next, and the attorney when neither applies. Finally, the people we work with, and the four core values of the PD Specialist role: urgency, attention to detail, empathy and being resolution driven. Before tomorrow, think about one scenario from today that surprised you, and bring a question about it. See you all tomorrow!",
   "scenario": "Exit ticket: a client calls and says, \"The other driver's insurance says it's still investigating, and my car is at a tow yard.\" In three sentences, tell her what you'll do today, which coverages you'll check, and when she'll hear from you next. Write your answer down and bring it tomorrow."
  }
 ]
});
